config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  get '/search', to: 'users#index'
  
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    
    collection { post :import}
    member do
      get 'working_index'
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    
    resources :attendances, only: :update
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  
  # remember_tokenという仮想の属性を作成する。
  attr_accessor :remember_token
  
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 }, 
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: true
  validates :department, length: { in: 2..30 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 },
                                    allow_nil: true
 
  # 渡された文字列のハッシュ値を返す。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためハッシュ化したトークンをデーターベースに記憶する。
  # ハッシュ化されたトークン情報の代入とトークンダイジェストの更新をする。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致すればtrueを返す。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了する。
    return fales if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # ログイン情報の破棄。（nilに更新）
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search) # ここでのself.はUser.を意味する
    if search
      where(['name LIKE ?', "%#{search}%"])# nameの部分一致検索
    else
      all
    end
  end
  
  def self.import(file)
    CVS.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つからなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CVSからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save!(validate: false)
    end
  end
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid",
     "basic_work_time", "designated_work_start_time",
     "designated_work_end_time", "superior", "admin", "password"]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :working_index, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:show, :edit, :update]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: [:working_index, :show]

  def index
    redirect_to(root_url) unless current_user.admin?
      @users = User.paginate(page: params[:page]).search(params[:search])
  end

  def working_index
    @user = User.find_by(params[:user_params])
    @users = User.all
    @attendance = Attendance.find(params[:id])
  end

  def import
    # fileはtmpに自動で一時保存される
    User.import(params[:file])
    redirect_to users_path
  end

  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "新規作成に成功しました。"
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit

  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
   
  end
  
  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  
  private
  
  
    def user_params
      params.require(:user).permit(:name, :email, :employee_number, :uid,
                                   :basic_work_time, :designated_work_atart_time,
                                   :designated_work_end_time, :superior, :admin,
                                   :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:department, :basic_time, :work_time)
    end
    
    def search
      @users = User.search(params[:search])
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
  
 # 勤怠基本情報を指定のフォーマットで返す。
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>
  
  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :employee_number, class: "form-control" %>

  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>
  
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>
  
  
  
  

app/views/users/_form2.himl.erb
<%= form_with(model: user, url: update_basic_info_user_path(user), local: true, method: :patch) do |f| %>
  <%= render 'shared/error_messages', object: user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>

  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :employee_number, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :uid, class: "form-control" %>
  
  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>
  
  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>
  
  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>
  
  <%= f.submit "更新", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_form2.html.erb
<%= form_with(model: user, url: update_basic_info_user_path(user), local: true, method: :patch) do |f| %>
  <%= render 'shared/error_messages', object: user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>

  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :employee_number, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :uid, class: "form-control" %>
  
  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>
  
  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>
  
  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>
  
  <%= f.submit "更新", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit') %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>

  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>

<h1><%= page_title %></h1>

<div class="import"> <%# CSVインポート %>
  <%= form_with url: import_users_path, class: "col-lg-4" do |form| %>
    <%= form.file_field :file, accept: '.csv' %><br>
    <%= form.submit "CSVをインポート", class: "btn btn-primary", style: "width: 300px" %><br>
    <h5>Example</h5>
  <% end %>
</div>

<%= will_paginate %>
<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover" id="table-users">

    <% @users.each do |user| %>
      <tr>
        <% if current_user.admin? && !current_user?(user) %>
          <td><%= user.name %><br>
            <span> | </span><%= link_to "削除", user, method: :delete, class: "btn btn-md btn-primary",
              data: { confirm: "削除してよろしいですか？" } %></br>
            <div class="panel-group">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <button type="button" class="btn btn-primary btn-lg"
                     data-toggle="collapse" data-target="#collapse<%= user.id %>">
                     編集</button>
                  </h4>
                </div>

                <div id="collapse<%= user.id %>" class="panel-collapse collapse">
                  <div class="panel-body">
                    <%= render 'form2', user: user %>
                  </div>
                </div>
              </div>
            </div>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>


<%= will_paginate %>

<!--モーダルウインドウ表示-->
<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>


<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td style="vertical-align: middle;">
        <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
        【<%= l(@first_day, format: :middle) %>】時間管理表
        <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-primary" %>
      </td>
      <td>
        指定勤務開始時間 : <%= format_basic_info(@user.work_time) %><br>
        指定勤務終了時間 : <%= format_basic_info(@user.work_time) %>
      </td>
      <td style="vertical-align: bottom;" colspan = "3">基本時間 : <%= format_basic_info(@user.basic_time) %></td>
      <td style="vertical-align: bottom;">初日 : <%= l(@first_day, format: :short) %></td>
    </tr>
    <tr>
      <td>所属 : <%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>氏名 : <%= @user.name %></td>
      <td>コード</td>
      <td></td>
      <td>出勤日数 : <%= @worked_sum %>日</td>
      <td>締め : <%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>


<div class="btn btn-users-show">
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
  <%= link_to "CSV出力", "#", class: "btn btn-primary" %><br>
  <%= link_to "勤怠修正ログ（承認済)", "#", style: "width: 100%;", class: "btn btn-primary" %>
</div>

<div>
  <table class="table table-bordered table-striped table-condensed table-hover" id="table-attendances">
    <thead>

      <tr> <!--rawspan:縦結合、colspan:横結合-->
        <th rowspan = "3">残業申請</th>
        <th rowspan = "3">日付</th>
        <th rowspan = "3">曜日</th>
        <th colspan = "8">【実績】</th>
        <th colspan = "5">所定外勤務</th>
      </tr>
      <tr>
        <th colspan = "3">出社</th>
        <th colspan = "3">退社</th>
        <th rowspan = "2">在社時間</th>
        <th rowspan = "2">備考</th>
        <th colspan = "2">終了予定時間</th>
        <th rowspan = "2">時間外時間</th>
        <th rowspan = "2">業務処理内容</th>
        <th rowspan = "2">指示者確認印</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
    
    <tbody>

      <% @attendances.each do |day| %>
        <% 
          css_class = 
          case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
          when '土'
            'text-primary'
          when '日'
            'text-danger'
          end
        %>
        <tr>
          <td><%= link_to "残業申請", "#", remote: true, class: "btn btn-primary" %></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class="<%= css_class %>">
            <%= $days_of_the_week[day.worked_on.wday] %>
          </td>
          <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
          <td><%= l(day.started_at.floor_to(15.minutes), format: :min) if day.started_at.present? %></td>
          
          <td> <!--繰り返し処理で表示している時間と本日が同じかつ出勤時間がからだったら、出勤ボタンを表示-->
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          
          <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
          <td><%= l(day.finished_at.floor_to(15.minutes), format: :min) if day.finished_at.present? %></td>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes)) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <% end %>
    </tbody>
    
    <tfoot>
      <!-- rowapan:縦結合、colapan:横結合 -->
      <tr>
        <td rowspan="3"></td>
        <td colspan="2"></td>
        <td colspan="6"></td>
        <td colspan="1"><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="5"></td>
        <td rowspan="3">
          <div class="control-label">所属長承認　未</label>
            <div>
              <select class="form-control">
                <option></option>
                <option>上長１</option>
                <option>上長２</option>
              </select>
            </div>
            <%= link_to "申請", "#", rimote: true, style: "width: 100%; margin-top: 5px;", class: "btn btn-primary" %>
        </td>
      </tr>
      <!--to_fメソッドは、文字列を浮動小数点数とみなしてFloatオブジェクトに変換する（to_iの小数点付きバージョン）-->
      <!--計算結果を小数点第２位までフォーマットしている。-->

    </tfoot>
  </table>
</div>

app/views/users/working_index.html.erb
<h1>出勤中社員一覧</h1>

<table class="table table-bordered table-condensed" id="table-users">
  <thead>
    <tr>
      <th>社員番号</th>
      <th>名前</th>
    </tr>
  </thead>
  <tbody>
      <% @users.each do |user| %>
        <tr>
            <% if @attendance.started_at.present? && @attendance.finished_at.nil? %>
              <td><%= @user.attendance.employee_number %></td>
              <td><%= @user.attendance.name %></td>
            <% end %>
        </tr>
      <% end %>
  </tbody>
</table>